name: graph_problems_dart
description: Solved some graph problems utilizing the Dart language.
version: 1.0.1
repository: https://github.com/maxeema/graph_problems_dart

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
